### ISSUE TITLE
Day skip success isn't updated

### ISSUE THREAD

**Issue by pifopi** [LegoFigure11/RaidCrawler#106]
Hello !

Small issue about day skip successes, it is no longer updating properly (it is set only once when you open the config window). Could it be updated afterward ? Manually needing to do this also mean you cannot stream that from OBS or anything as it requires human intervention

Thanks !

**Comment by architdate** [comment]
Why would you need to stream date skip successes? isn't the point of it to know how well it has performed with delays? It is infeasible to update it within a separate form unfortunately so this cannot be done since success/failures are tracked in the main window.

**Comment by pifopi** [comment]
To be able to check how the program is doing remotely. Also, even locally, the succes rate cannot be tracked while editing the settings, making it not very practical to use.

I kinda expected it to be impossible because i feel the change that was made kinda breaks encapsulation. I'll move it back on my fork, thanks for the answer !

**Comment by architdate** [comment]
The success rate should still be tracked while settings window is open!

**Comment by pifopi** [comment]
but it isn't updated so after each change, you need to close, reopen and switch back to the right tab. That's a lot of mouse click :(
