### ISSUE TITLE
Batch Editor Non-functional?

### ISSUE THREAD

**Issue by CakeFlour** [LegoFigure11/RaidCrawler#109]
Attempting to use batch filter causes RaidCrawler to signal false positives regardless of whats typed into it.

In the "Edit filters window" you can type anything into batch and create a new filter with it. The Raid crawler then will say it's found a matching pokemon every time the date is advanced. and skips to the last raid in the list. 

I attempted to set a filter to search for Max/Min Size pokemon using the batch editor value ".Scale=255" and it didn't work
Unsure if this is an accurate result of incorrect syntax, or it just fails to work.
(note: using "=Scale=255" doesn't cause the false flag, but doesn't trigger anything at all)

**Comment by architdate** [comment]
=Scale=255 should work, filters are either prefixed with . or !
Since you are filtering it to stop on max scale, it is unlikely that it will trigger soon. scale 255 is rather rare.

**Comment by CakeFlour** [comment]
> =Scale=255 should work, filters are either prefixed with . or ! Since you are filtering it to stop on max scale, it is unlikely that it will trigger soon. scale 255 is rather rare.

Tested with some more values and it does work as intended. Thank-you.
