### ISSUE TITLE
South Area 4 listed as South Area 5 -- with pictures!

### ISSUE THREAD

**Issue by spacesonata** [LegoFigure11/RaidCrawler#11]
1st
![example1](https://user-images.githubusercontent.com/86179327/204360809-d9b6f21f-acdd-4d6c-affc-20dfb2b3675b.JPG)
![IMG_0517](https://user-images.githubusercontent.com/86179327/204360830-7ec0bbee-ee1e-4528-8f17-1f0d682a474b.PNG)
![IMG_0518](https://user-images.githubusercontent.com/86179327/204360844-0f92b34e-2765-4469-8ab1-dc787cae7216.PNG)

2nd
![example2](https://user-images.githubusercontent.com/86179327/204360854-563b62c2-86d7-4050-980b-111699cacb00.JPG)
![IMG_0519](https://user-images.githubusercontent.com/86179327/204360872-69c65712-2347-4957-b09e-ce7b3471890f.PNG)
![IMG_0520](https://user-images.githubusercontent.com/86179327/204360897-58215fde-cea0-4ef7-af59-a52bf6057dc9.PNG)

3rd
![example3](https://user-images.githubusercontent.com/86179327/204360942-bdf87a9c-5b36-4c0e-894c-16e56f90fb94.JPG)
![IMG_0521](https://user-images.githubusercontent.com/86179327/204360964-82baa25e-32dd-4259-b711-eda733e60be1.PNG)
![IMG_0522](https://user-images.githubusercontent.com/86179327/204360986-79a14db4-27d6-4e4e-b54c-0c26d6cf225c.PNG)

These three were listed as South Area 5 and match with RaidCrawler
![InkedIMG_0516](https://user-images.githubusercontent.com/86179327/204361428-1f479946-f29e-4a6f-9d43-7b1099b97082.jpg)

I assume it's just a typo :)

**Comment by LegoFigure11** [comment]
Thanks for the report!
