### ISSUE TITLE
Non-Emoji Stars inserting incorrectly

### ISSUE THREAD

**Issue by thatmatthallett** [LegoFigure11/RaidCrawler#110]
When the Enable Emoji Option is uchecked the default star emoji that is used is inserting incorrectly as :star and not :star: causing an output that looks like this (for a 5 star raid):
⭐star⭐star:star

![image](https://user-images.githubusercontent.com/1817529/213777236-5a52f64f-8ba2-42a1-b415-493496f61ef0.png)

From what I can tell browsing the Git the error is on lines 128-130 of NotificationHandler.cs
![image](https://user-images.githubusercontent.com/1817529/213777479-b547a72a-74eb-4a3e-8d05-b2655a740097.png)

":star" should be ":<zero-width space>star:"

**Comment by LegoFigure11** [comment]
Thanks for the report!
