### ISSUE TITLE
fails to date advance

### ISSUE THREAD

**Issue by Turallad** [LegoFigure11/RaidCrawler#111]
when set to overshoot every so often when skipping instead of going down to console battery then moving back up to date and time it will go down to stereo and then back up to console battery so fails to actually advance the date

**Comment by LegoFigure11** [comment]
Ensure your connection is as strong as possible. You may have to adjust the timings in Settings -> Advance Date, and if it's still unstable then de-select "Use overshoot"

Suggested timings can be found in the guide: https://billo-guides.github.io/cfw/sv/raidcrawler/
