### ISSUE TITLE
10 foot view text field not disabled

### ISSUE THREAD

**Issue by tombomb** [LegoFigure11/RaidCrawler#112]
**Describe the bug**
You can type into the 10foot view text field 

**To Reproduce**
If applicable, please list the steps to reproduce the behavior:
1. Open 10 foot view
2. click into the den location info
3. type

**Expected behavior**
Its disabled and can only be updated by the program

**Raid Data**
01 00 00 00 01 00 00 00 01 00 00 00 06 00 00 00 E6 CA F2 BC 00 00 00 00 00 00 00 00 00 00 00 00

**Screenshots**
![image](https://user-images.githubusercontent.com/544509/213945505-a07f6c6c-58c3-410d-85aa-ba2146eaf741.png)

**Additional context**
version 1.1.0

**Comment by LegoFigure11** [comment]
This is actually intended! I've seen a lot of hosts edit this field to contain the raid code when posting screenshots to discord servers :)
