### ISSUE TITLE
1 star raids: IVs predicted do not match result

### ISSUE THREAD

**Issue by jintsuu** [LegoFigure11/RaidCrawler#12]
![image](https://user-images.githubusercontent.com/51126376/204623350-9d120810-79a6-4903-bf66-75e7f121fc07.png)
![image](https://user-images.githubusercontent.com/51126376/204623398-bd0deca5-1201-427c-b705-8d734474eb58.png)

Might have to do with the fact that 1 perfect IV is guaranteed and the program not accounting for it?

**Comment by architdate** [comment]
Sorry about that, I will be fixing this in the latest commit! Thanks for pointing this out!
![image](https://user-images.githubusercontent.com/17220860/204676900-da6e00b0-80ff-4d23-aaf5-6dcac89a7ea9.png)
