### ISSUE TITLE
Failure to Advance Date

### ISSUE THREAD

**Issue by TJP3-Github** [LegoFigure11/RaidCrawler#122]
**Bug**
RaidCrawler v.1.1.0 date advancement has approximately 50% failure rate.
Rather than selecting "Date and Time" in the System Settings menu, it will instead select "Console Battery (%)" or "Console Sound"

**To Reproduce**
Easily reproduceable; This is occurring with strong WiFi connection, nearly doubling the time requirement to obtain a Shiny Tera Raid.

**Expected behavior**
Switch Menu --> System Settings --> System --> Date and Time

**Screenshots**
I've attached a captured .MP4 video file, to clearly show this bug in action:
https://user-images.githubusercontent.com/66980268/214954859-084874a5-ff0c-4faa-a28a-0912fbdf3dcf.mp4

**Additional context**
Previous version v.1.0.9 of RaidCrawler (actually v.1.0.8, since the .9 download included wrong version) does not have this issue.

**Comment by lfmundim** [comment]
That is weird, I've been using 1.1.0 since release for about 8h a day and i haven't noticed that behavior. I have noticed some weird stuff going on if the cursor on the home menu isn't where it expects it to be, but not nearly as 50% of the time... can you share your raidcrawler settings?

**Comment by LegoFigure11** [comment]
Improve your connection (move your switch and computer closer to your router) or disable overshoot and go back to using DDOWN presses.

See the section here on Date Skipping and associated troubleshooting: https://billo-guides.github.io/cfw/sv/raidcrawler/#SettingsInfo
