### ISSUE TITLE
Filter Settings: Batch Filter issue

### ISSUE THREAD

**Issue by ReZeroEmiria** [LegoFigure11/RaidCrawler#124]
> =Scale=255 should work, filters are either prefixed with . or ! Since you are filtering it to stop on max scale, it is unlikely that it will trigger soon. scale 255 is rather rare.

Tested with some more values and it does work as intended. Thank-you.

_Originally posted by @CakeFlour in https://github.com/LegoFigure11/RaidCrawler/issues/109#issuecomment-1397850410_
            

Greetings, I'm trying to use the filter settings for "Any Shiny" by only clicking the "Shiny?" box and updating filter. In order to not stop on duplicate pokemon I have already caught I tried to add the following line in the batch filters:
           
           !Species=974

This would be a "do not = cetoddle" so I assumed it would search for any shiny EXCEPT Cetoddle and any others like if I used

!Species=974
!Species=25

This would make it so it wouldn't stop on Cetoddle OR Pikachu, right?
Am I misunderstanding or is there something wrong with this feature, please let me know!

**Comment by architdate** [comment]
Your understanding is correct! I would however advice waiting for the next update with updated pkhex core files and drawing/dll files. Currently the species numbers are not the official dex numbers. The latest core update adheres to appropriate national Dex nomenclature.

**Comment by ReZeroEmiria** [comment]
Thank you for the confirmation! I'll save the lines I've written for the filter files then and test them during next release! 
I remember there was a link to try out the latest nightly/build, is this still a thing? If it's already been implemented I'd like to try it if possible, please let me know!

Originally I thought the species would be the string names but when I tried to use

!Species=Cetoddle

I got an error on the program and it wouldn't let me run anything. With dex numbers it does run though just like you mentioned it's not properly set up yet. Is there a table somewhere with each pokemon and it's dex number btw?
