### ISSUE TITLE
Suggestion/Feature: send errors on webhook.

### ISSUE THREAD

**Issue by kusax01** [LegoFigure11/RaidCrawler#126]
Hi! It's only a suggestion, but, do you guys think it's possible to change the program, that if RaidCrawler finds any error/issue while rolling, it sends the error message over the webhook?

It's not very common, but sometimes, it is stopped, and the only way to know, if to go back to the switch or RC PC, if the webhook sends a message, then you can go check the error and get the RC rolling again

**Comment by Koi-3088** [comment]
Implemented with [7f5bb95](https://github.com/LegoFigure11/RaidCrawler/commit/7f5bb950f735f7a47c33f068179d247dfb1f351a)
