### ISSUE TITLE
[v1.1.0] Ceruledge / Armorouge Event Missing Data (Violet Issue)

### ISSUE THREAD

**Issue by jnovack** [LegoFigure11/RaidCrawler#127]
**Describe the bug**
No event pokemon for Cereledge / Armorouge event

**To Reproduce**
1. Reopen Raidcrawler
2. Read Raids
3. Notice first few are empty

**Expected behavior**
Ceruledge to be showing

**Raid Data**
01 00 00 00 0E 00 00 00 01 00 00 00 06 00 00 00 C7 46 99 A1 00 00 00 00 02 00 00 00 00 00 00 00

Absolute Address: 4B84803040

**Screenshots**
![image](https://user-images.githubusercontent.com/387006/216479602-98b4db9e-a994-497c-b242-97985eb8e90d.png)

Affects v1.1.0 Release

**Comment by jnovack** [comment]
This seems to be Violet specific.

**Comment by LegoFigure11** [comment]
Fixed by db00656

**Comment by jnovack** [comment]
Are you bumping the version and release so that people can download it?
