### ISSUE TITLE
Crashing whenever opening

### ISSUE THREAD

**Issue by darthvader1043** [LegoFigure11/RaidCrawler#129]
Raid crawler is crashing whenever i open it, don't know why but it started with an event raid and ever since it hasn't worked. 
[message (1).txt](https://github.com/LegoFigure11/RaidCrawler/files/10727600/message.1.txt)
![image-1](https://user-images.githubusercontent.com/78067812/218611037-26399838-cf7c-467c-93cd-a39904359748.png)
Included is a picture of what i see on the screen as well as the full error code it spat out at me. I have tried deleting the config.json file but that didn't help at all.
Assistance with this would be appreciated. Thanks

**Comment by LegoFigure11** [comment]
Are you able to test this on the latest dev build? https://nightly.link/LegoFigure11/RaidCrawler/workflows/dotnet-desktop/main/RaidCrawler.zip

You might also need to .NET 7 runtime from https://dotnet.microsoft.com/en-us/download/dotnet/7.0

**Comment by LegoFigure11** [comment]
Going to close this as I can't replicate. Please feel free to reopen if you are able to reproduce it on the latest dev build!
