### ISSUE TITLE
Suggestion/Feature: Scale size as a filter

### ISSUE THREAD

**Issue by remi2k7** [LegoFigure11/RaidCrawler#132]
was wondering if it would be possible to add scale size as a filter because the Pikachu event has a chance of also getting the Jumbo mark and maybe future events will have something similar.

**Comment by LegoFigure11** [comment]
Scale can currently be searched for using batch filters, I won't implement it outside of these.

As far as the Pika event is concerned, I am not available to research how it is stored or calculated until mid-next week. If you are able to tell me where it's stored in the flatbuffer and how it is calculated, I will implement it sooner. As it stands, RaidCrawler is not able to search for a Pikachu with a specific scale.

**Comment by WolfByte01** [comment]
> Scale can currently be searched for using batch filters, I won't implement it outside of these.
> 
> As far as the Pika event is concerned, I am not available to research how it is stored or calculated until mid-next week. If you are able to tell me where it's stored in the flatbuffer and how it is calculated, I will implement it sooner. As it stands, RaidCrawler is not able to search for a Pikachu with a specific scale.

Ah alright, thanks for this info.

**Comment by WolfByte01** [comment]
is the batch command for scale =scale= or .scale= . I'm not familier with batch commands.

**Comment by LegoFigure11** [comment]
You can try this (untested) build in the meantime: https://cdn.discordapp.com/attachments/1042987779040215050/1079691321465389126/RaidCrawler.zip

Set a batch filter with `=Scale=255`

**Comment by WolfByte01** [comment]
> You can try this (untested) build in the meantime: https://cdn.discordapp.com/attachments/1042987779040215050/1079691321465389126/RaidCrawler.zip
> 
> Set a batch filter with `=Scale=255`. If it works I'll push it.

Worked fine for finding Jumbo Pika.
