### ISSUE TITLE
Save Block not found

### ISSUE THREAD

**Issue by CrackedOutCrabby** [LegoFigure11/RaidCrawler#136]
**Describe the bug**
Every time i try to connect to game with ip, i get the error 
" Specified argument was out of range of valid values.
  (Parameter 'Save block not found in range +- 0x1000') "

**To Reproduce**
If applicable, please list the steps to reproduce the behavior:

**Expected behavior**
To just connect to my switch and find raids
![Screenshot 2023-03-13 150227](https://user-images.githubusercontent.com/127797843/224842080-f6ca2265-57b7-4430-9f78-fc04bbde5a57.png)

**Raid Data**
If the result you see in the program does not match what you see in-game, please click "Dump Raid" and replace this text with the bytes in the window that pops up.

**Screenshots**

**Additional context**

**Comment by itsteeb07** [comment]
click on 'build passing' at the bottom of the page, use that version

**Comment by Melfear** [comment]
I had the same issue and my workaround was to install Visual Studio Cummunity Edition, load the repo from git within VS, build, copy my config.json and filter.json file into my bin/debug folder and run it into debug mode within VS. I'll try using the build outside VS later but for now it's Raid Crawler time :)

**Comment by LegoFigure11** [comment]
This should have been fixed by 2d64d0c, if the issue persists on latest nightly then please feel free to reopen!
