### ISSUE TITLE
Feature Request: Jump to stop condtion raid button

### ISSUE THREAD

**Issue by tombomb** [LegoFigure11/RaidCrawler#14]
It would be nice to have a 1 click button to jump to the raid that is shiny / your stop condition. Maybe a second set of arrows below the current arrows that jumps to raids that have met your stop condition on the off chance that you have like "stop on shiny" and you get 2 shiny raids.

**Comment by LegoFigure11** [comment]
This already exists! Simply Shift+Click on either of the arrow buttons to jump to the next raid in the list that satisfies your stop conditions. 

I'll add it to the user guide so that more people can know about it.

**Comment by tombomb** [comment]
You are a god lego <3
