### ISSUE TITLE
Webhooks not firing when result is found

### ISSUE THREAD

**Issue by WildEep219** [LegoFigure11/RaidCrawler#142]
**Describe the bug**
I'm on the latest build of RaidCrawler and have a webhook configured. Testing the webhook results in the raid being sent to Discord appropriately, but when RaidCrawler stops because it found something, I don't see a webhook notification in my Discord server.

**To Reproduce**
If applicable, please list the steps to reproduce the behavior:
1. Configure a webhook, and click Test Webhook to confirm a message is sent to Discord.
2. Advance date with filters enabled.
3. Let RaidCrawler find a match.
4. No message in Discord.

**Expected behavior**
Released versions of RaidCrawler would send a message to Discord if configured when it finds a match.

**Comment by Koi-3088** [comment]
Thanks. Latest commit should fix this once it's done building.

**Comment by WildEep219** [comment]
Looks like the latest commit did fix this. Thank you!
