### ISSUE TITLE
Incorrect Distribution Ditto Nature and IVs for forced-0 encounters

### ISSUE THREAD

**Issue by WildEep219** [LegoFigure11/RaidCrawler#143]
**Describe the bug**
For the Ditto distribution, RaidCrawler can report incorrect nature and IVs for at least the guaranteed 31/31/31/31/31/0 and 31/0/31/31/31/31 Dittos. Seed, PID, and EC appear to be correct.

**To Reproduce**
If applicable, please list the steps to reproduce the behavior:
1. Advance date until you encounter a distribution Ditto with fewer than 5 flawless IVs according to RaidCrawler.
2. Catch the Ditto and notice its IVs and nature are different from what RaidCrawler reported.

**Expected behavior**
Ideally report the correct nature and IVs for these special Dittos.

**Raid Data**
For the following raid block:
01 00 00 00 0A 00 00 00 01 00 00 00 07 00 00 00 7C D3 F1 FC 00 00 00 00 02 00 00 00 00 00 00 00

RaidCrawler reports that it is Quirky with the IVs 26/21/04/12/30/25. However when I caught it, it was actually Gentle 31/31/31/31/31/0 (No good Speed).

For this raid block from a separate day:
01 00 00 00 0F 00 00 00 01 00 00 00 09 00 00 00 E4 3A 5A 97 00 00 00 00 02 00 00 00 00 00 00 00

RaidCrawler reports that it is Hasty with the IVs 21/29/07/14/22/01, but when captured, it was actually Gentle 31/0/31/31/31/31 (No good Attack)

**Comment by Koi-3088** [comment]
Thanks. See if the latest commit fixes it (and doesn't break regular raids) once it's done building.

**Comment by WildEep219** [comment]
RaidCrawler reported that this raid block was a Careful 31/31/31/31/31/31 distribution Ditto, but after catching it, it turned out to be Mild natured.

Raid block:
01 00 00 00 08 00 00 00 01 00 00 00 0D 00 00 00 52 2B EA 07 00 00 00 00 02 00 00 00 00 00 00 00

**Comment by Lusamine** [comment]
The first two you have are both 1% slots with all 6 IVs fixed. If the calculation is done with all the IV generation, gender calculation, and ability generation skipped, it produces the correct nature.

> RaidCrawler reported that this raid block was a Careful 31/31/31/31/31/31 distribution Ditto, but after catching it, it turned out to be Mild natured.
> 
> Raid block: 01 00 00 00 08 00 00 00 01 00 00 00 0D 00 00 00 52 2B EA 07 00 00 00 00 02 00 00 00 00 00 00 00

I caught this exact Ditto on a completed game and it was Careful as predicted. This one is one of the 97% 5 IV Ditto. Do you have the file for the one you caught?

**Comment by WildEep219** [comment]
I do have the file (attached as a zip because GitHub doesn't like pk9 files).

[132 - Ditto - 74312F9D504D.zip](https://github.com/LegoFigure11/RaidCrawler/files/11182473/132.-.Ditto.-.74312F9D504D.zip)

**Comment by Koi-3088** [comment]
>For the following raid block:
01 00 00 00 0A 00 00 00 01 00 00 00 07 00 00 00 7C D3 F1 FC 00 00 00 00 02 00 00 00 00 00 00 00
>
>RaidCrawler reports that it is Quirky with the IVs 26/21/04/12/30/25. However when I caught it, it was actually Gentle 31/31/31/31/31/0 (No good Speed).

![image](https://user-images.githubusercontent.com/61223145/230702369-4f47e221-c572-4dd4-9cba-64b2babf5fb7.png)

And Anubis said that this Ditto here
>01 00 00 00 08 00 00 00 01 00 00 00 0D 00 00 00 52 2B EA 07 00 00 00 00 02 00 00 00 00 00 00 00

does result in Careful when caught. Are you using the latest passing build? I did push a commit just now but it should be irrelevant to this issue (minor readability changes and Anubis' date advance routine).

**Comment by WildEep219** [comment]
Nope, just trolled by this raid block in the same batch:

01 00 00 00 07 00 00 00 01 00 00 00 03 00 00 00 F2 E5 FF 0C 00 00 00 00 02 00 00 00 00 00 00 00

PEBKAC error here.

**Comment by Koi-3088** [comment]
Thank you for bringing up the original issue to my attention though, I'll mark this one as closed for now then.
