### ISSUE TITLE
Value cannot be null when trying to connect

### ISSUE THREAD

**Issue by Chaos192** [LegoFigure11/RaidCrawler#144]
![image](https://user-images.githubusercontent.com/9710259/230742726-728e4c58-da28-471f-a82b-f09a312c8a87.png)

**Comment by Koi-3088** [comment]
Have you tried to delete the cache folder?

**Comment by Spade013** [comment]
I'm having the same issue. I deleted the cache folder and it still is giving me the error code.

**Comment by Koi-3088** [comment]
The only way I can replicate this is by improperly overwriting raid blocks in my save. All I can think of to suggest trying is to skip a day so raids change, getting latest event news, saving, then deleting the cache and then trying to connect.

Otherwise I don't know how to replicate since even very old saves work fine for me on both games.

**Comment by Lusamine** [comment]
I can replicate this error by clearing only the 7 star raid. Did you guys (@Chaos192, @Spade013) do anything to the raids on the map before you got the error?

**Comment by Spade013** [comment]
I do not have 7 star raids unlocked yet. Before I tried this, I just finished the game on this console to unlock the 5 star raid for the event.

**Comment by Koi-3088** [comment]
Would you mind sending me the save that causes the error? You could either zip in here (I'd delete shortly), or via DM on Discord (Koi#3088).

**Comment by Spade013** [comment]
I can when I get home from work in the morning.

**Comment by Koi-3088** [comment]
@Spade013 @Chaos192 Sorry for the delay. I just pushed a commit that should hopefully fix this issue, let me know if it works or if there are any issues once it's done building.

**Comment by Spade013** [comment]
What do I need to do to use this? My programming skills are almost non-existent, however I can at least give it a try so I can help out in the future.

**Comment by Koi-3088** [comment]
You just need to click the green "build passing" icon on the main page of this repository.

**Comment by CrossL92** [comment]
I had the same issue before but this has fixed it for me.

**Comment by Spade013** [comment]
It worked! Thank you so much!
