### ISSUE TITLE
Filter not always working for the Ditto event.

### ISSUE THREAD

**Issue by ruanick** [LegoFigure11/RaidCrawler#145]
I have a save file that hasn't connected to the internet since the event and still has the Ditto raids. I set up filters for 0 Attack and 0 Speed Ditto but have noticed they don't always trigger. This is happening on the current nightly build, v1.1.1-3b15e09.

I've attached screenshots of a save with two 31/00/31/31/31/31 Ditto raids on the map while RaidCrawler says 0 matches. I went and captured the adamant one to confirm it was 31/00/31/31/31/31. 

The third screenshot is from clicking "Advance Date" immediately after the above where a 31/31/31/31/31/00 Ditto was successfully identified by the filter. From what I can tell the two filters were configured identically except for the position of the 0 IV.

I can provide a save from before I captured the adamant one if it's helpful. I changed the extension of my filter.json to filters.txt so I could attach it here.

[filters.txt](https://github.com/LegoFigure11/RaidCrawler/files/11194038/filters.txt)
![bug](https://user-images.githubusercontent.com/127425945/230998251-9d75ee81-64ad-472b-a500-cb9899d2a4b6.png)
![bug2](https://user-images.githubusercontent.com/127425945/230998253-7d323afe-91a9-46f7-b66a-da7fd44db77a.png)
![bug4](https://user-images.githubusercontent.com/127425945/231001789-284274a0-adb0-4ac4-84d7-08b7fbfa02e7.png)

**Comment by Koi-3088** [comment]
Pushed a commit that should hopefully fix it. Let me know if it works.

**Comment by ruanick** [comment]
Thanks for the update, it seems to have resolved some of the issue. I loaded the previously mentioned save and set the system date to preserve the dens. RaidCrawler immediately identified the two matching dens that it missed before.

I started advancing one day at a time and manually verifying the filters to see if it would miss any.
First Skip: Failed to identify a 0 Spd Ditto. 
Second Skip: Succeeded in identifying a 0 Atk Ditto.
Third Skip: Succeeded in identifying a 0 Spd Ditto.
The filters worked correctly for the 4th and 5th skips.
Sixth Skip: Failed to identify a 0 Spd Ditto. 

I made a save back-up after the sixth skip and will continue skipping later to see if it still misses any 0 Atk. I probably should have left the Shiny filter off during testing but I clicked though all of the dens to confirm that the matching instances correctly referred to Dittos and nothing else.

![fixed1](https://user-images.githubusercontent.com/127425945/232252854-86a3c82e-f7c1-4cde-81f5-70a59c6c57c0.png)
![spdbug](https://user-images.githubusercontent.com/127425945/232252862-d08a6568-2ee9-4fc5-add1-badcb4b81b5f.png)
![workingatk](https://user-images.githubusercontent.com/127425945/232252866-7d01e3f9-9104-42a2-833c-ea27d8d1cd00.png)
![workingspd](https://user-images.githubusercontent.com/127425945/232252873-52ec1908-2e3c-4a4a-bbe4-04569dcf6e5e.png)
![spdbug2](https://user-images.githubusercontent.com/127425945/232252883-f9895a87-5030-49aa-8873-7b97396f5740.png)

**Comment by Koi-3088** [comment]
Thank you for testing and noticing, try out the latest commit once it finishes building.

**Comment by ruanick** [comment]
It looks like that did the trick. I loaded the 0 Spd Ditto save from the previous test and RaidCrawler identified a match. I checked 15 days and every 0 Atk and 0 Spd Ditto was correctly identified. 

Thanks for the help!
![fixed](https://user-images.githubusercontent.com/127425945/232261842-94e39d4d-cd4e-4395-b65c-da0ac6bc9edc.png)
