### ISSUE TITLE
"Event out of priority range"

### ISSUE THREAD

**Issue by TJP3-Github** [LegoFigure11/RaidCrawler#148]
The following error is occurring, and I have no idea what it means and/or how to correct it:
![RaidCrawler Error](https://user-images.githubusercontent.com/66980268/235466161-73e0d034-bb75-4520-9382-c2eb292c4b6f.JPG)

**Comment by Banzail** [comment]
Walking Wake/Iron leaves raid causes this problem to be precise. If that raid is not in ram/complete. Works like usually does

**Comment by Koi-3088** [comment]
Let me know if there are any issues with the latest commit.

**Comment by TJP3-Github** [comment]
The issue seems to be resolved as of the latest nightly build 👍
