### ISSUE TITLE
"No encounters found for the given distribution raid."

### ISSUE THREAD

**Issue by UserUnavailablee** [LegoFigure11/RaidCrawler#149]
I've been getting this message a lot since the last RaidCrawler update. Is there a way to disable it, or to solve this issue? If I close it then it'll start advancing date again, but otherwise it stops all progress. Sorry if there was already a post!! I didn't find one under a similar name.

![image](https://user-images.githubusercontent.com/91800133/236634268-8827cffb-a047-4364-868b-4d6868743dbb.png)
![image](https://user-images.githubusercontent.com/91800133/236634382-b11eb901-1c58-4674-9de7-1443ca2800c3.png)

**Comment by Koi-3088** [comment]
Try deleting the cache folder or repulling raid data.

**Comment by UserUnavailablee** [comment]
Work perfectly! Thank you sm

**Comment by UserUnavailablee** [comment]
Well, it worked for a while, same issue came up, this time clearing cache did nothing

**Comment by Koi-3088** [comment]
There are buttons "read raids" and "pull events". But deleting the cache folder and restarting the app accomplishes the same thing.

Are you using the latest release or the latest passing build? Latest release would not have the latest fixes.

**Comment by UserUnavailablee** [comment]
I'm currently using the latest release, how would I create the latest passing build?

**Comment by Koi-3088** [comment]
You'd click the green "build passing" icon on the main repository page.
![image](https://user-images.githubusercontent.com/61223145/236643974-5132be5e-6948-42f3-9a0f-b3d74003ccdd.png)

**Comment by UserUnavailablee** [comment]
Thanks! That worked perfectly
