### ISSUE TITLE
Image of teratype occult the number of shiny raids

### ISSUE THREAD

**Issue by edwarbad23** [LegoFigure11/RaidCrawler#15]
![dsdsddddd](https://user-images.githubusercontent.com/21049981/204709903-21d1cdb2-efe9-45be-98ab-a28e3aa5e918.jpg)

**Comment by LegoFigure11** [comment]
Can't reproduce on my machine? Possibly a Win10 vs Win11 thing
![](https://images-ext-2.discordapp.net/external/RncgQxH3Ysthe3ZU7gnfo4OOoIpYtQr6gHu8zumVlKI/https/i.imgur.com/bm9P0RQ.png)

I'll make the text shorter to account for this though.
