### ISSUE TITLE
SV 1.3.2 Support

### ISSUE THREAD

**Issue by Jacktender** [LegoFigure11/RaidCrawler#153]
RaidCrawler has no trouble connecting to my switch and it was even working fine yesterday, but now it doesn't get past the "Reading event raid status..." prompt. Could be because of the 1.3.2 update for SV today?

**Comment by LegoFigure11** [comment]
Yes, the new SV update has changed the offsets so RaidCrawler will not work until we are able to update it. Your patience is appreciated!

**Comment by LegoFigure11** [comment]
Addressed by #154
