### ISSUE TITLE
A Show of Supporters raid distribution causing Sequence contains no elements error

### ISSUE THREAD

**Issue by WildEep219** [LegoFigure11/RaidCrawler#158]
**Describe the bug**
After updating to the latest raid distribution (Blissey/Grimmsnarl/Hatterene), trying to connect to the Switch results in the error "Error occurred while reading raids: Sequence contains no elements".

**To Reproduce**
If applicable, please list the steps to reproduce the behavior:
1. Download the latest raid distribution data.
2. Try to connect to the Switch with RaidCrawler.
3. "Error occurred while reading raids: Sequence contains no elements"

**Expected behavior**
Expected behavior is to connect without an error.

**Raid Data**
Unable to get raid data at all.

**Comment by LegoFigure11** [comment]
Seems to b working on the latest commit build for me? Please try on https://nightly.link/LegoFigure11/RaidCrawler/workflows/dotnet-desktop/main/RaidCrawler.zip and delete the `cache` folder if necessary.

**Comment by WildEep219** [comment]
That did the trick. Thanks and sorry for the inconvenience!
