### ISSUE TITLE
Error generating map

### ISSUE THREAD

**Issue by CardBreaker** [LegoFigure11/RaidCrawler#163]
**Describe the bug**
When you click Open Map, RC shows a pop up saying it couldn't generate the map. This seems to occur for raids in Apple Hills. I've had this occur on both Apple Hills - Den 12 and Apple Hills - Den 15.

**To Reproduce**
1. Start advancing the date.
2. Find a raid in Apple Hills.
3. Click Open Map.
4. Pop up appears.

**Expected behavior**
Map should be generated like they do for other locations.

**Screenshots**
![image](https://github.com/LegoFigure11/RaidCrawler/assets/43624643/027f4a3c-6458-49a2-a942-f205ec0ccefe)

**Comment by CardBreaker** [comment]
I see the issue. keys 1-2-12 and 1-2-15 and presumably other dens in Apple Hills above 10 don't exist in den_locations_kitakami.json.

**Comment by LegoFigure11** [comment]
Yup, a few locations were missing from the dump for whatever reason. You can help us by providing your player coords standing at the den where the raid actually is (or providing a save standing there if you don't know how to get coords) so we can fill in the blanks!

**Comment by CardBreaker** [comment]
Great, I plan to put aside some time later today to put this together. I can open a PR with the changes when that's ready.
