### ISSUE TITLE
Feature Request - Filters Toggle

### ISSUE THREAD

**Issue by TJP3-Github** [LegoFigure11/RaidCrawler#165]
For RaidCrawler users who have dozens of specific filters created, it would be very helpful to have the ability to Toggle On/Off all Filters at once. 

![RaidCrawlerToggleAllFeatureRequest](https://github.com/LegoFigure11/RaidCrawler/assets/66980268/a760d73b-9e7d-416d-959e-af381dfdef16)

**Comment by LegoFigure11** [comment]
You can use the "Enable Filters" checkbox on the main window to enable/disable all filters
![image](https://github.com/LegoFigure11/RaidCrawler/assets/24732684/c90ba6f7-167e-4545-a4a0-253f39eaaa5b)
