### ISSUE TITLE
Index outside Array

### ISSUE THREAD

**Issue by 13blarg** [LegoFigure11/RaidCrawler#168]
**Describe the bug**
While running the bot I'm getting an error message saying index outside array, which terminates the date advancing.

**Additional context**
![RaidCrawler Issue](https://github.com/LegoFigure11/RaidCrawler/assets/95506452/9b4af40c-667b-4cfe-8254-802106574c43)

I don't have the DLC.

**Comment by LegoFigure11** [comment]
Cannot repro, please verify you still run in to this on the latest release?

**Comment by thuanle123** [comment]
I also ran into this problem on v2.0.0 and i cannot identify the cause, i will report back for v2.0.1 in a couple days
I have try to narrow down to a few thing

1. First i think maybe my switch is overheat which cause it to go to sleep mode which could cause date advance failed, switch cpu is fine
2. then, i thought about my computer going into sleep mode, nope sleep mode is set to never and only screen is set to be turn off after certain amount of time
3. Internet connection, nope all of them are Ethernet
4. And it varies too, sometimes i can go up to 2500 no problem, sometimes it stops after 200, sometimes it stops after 5 minutes

**Comment by LegoFigure11** [comment]
If possible, a save file dump with faulty raids on it would be very helpful for debugging this. Feel free to DM one to me on discord if you run in to it again!

**Comment by LegoFigure11** [comment]
Closing as stale + can't repro, feel free to reopen if you're still running in to this issue!
