### ISSUE TITLE
Bug? - Camera...

### ISSUE THREAD

**Issue by brianomatic1** [LegoFigure11/RaidCrawler#17]
During long searches, sometimes the camera app opens in game. 

This is a purely "cosmetic" issue and does not affect the utility in any way from it's task.

**Comment by LightSanctity** [comment]
Hi I had this issue too; can you try and move your switch closer to your router. Mine was far away and often changed the timezone, enter into picture mode, and other things.

**Comment by brianomatic1** [comment]
all of my switches are hard wired.

**Comment by LegoFigure11** [comment]
Yup, LightSanctity is correct -- this occurs when the console fails to register a HOME press, leading to it (eventually) pressing DDOWN on the overworld, opening the camera. It can be usually be remedied by moving the console and/or your computer closer to the router, or if needed you can adjust the timings in https://github.com/LegoFigure11/RaidCrawler/blob/main/MainWindow.cs#L295 and recompile. I do plan on adding settings to make these settings easier to change in the future.
