### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by Inforen2** [LegoFigure11/RaidCrawler#18]
https://user-images.githubusercontent.com/119541709/204916795-7af7d2b8-dafe-4a57-9923-a34b1b48e1b0.mp4

In the process of my use, when the program automatically adjusts the time, it always selects "remaining power of the host" under "date and time", which can't realize automation. I hope it can be fixed as soon as possible, and the number of times of using the "down" button can be adjusted.

**Comment by tombomb** [comment]
mine only seems to work when docked, try that

**Comment by Inforen2** [comment]
My device is switch lite. It has no docked mode。

**Comment by LegoFigure11** [comment]
Duplicate of #7
