### ISSUE TITLE
Feature Request: Select Multiple Pokemon

### ISSUE THREAD

**Issue by mwoerner77** [LegoFigure11/RaidCrawler#24]
If possible, selecting a limited group of pokemon to search for instead of one would make shiny hunting for new generation pokemon easier

**Comment by mwoerner77** [comment]
One implementation of this is in my fork https://github.com/mwoerner77/RaidCrawler/tree/MultiselectSpecies

**Comment by LegoFigure11** [comment]
@mwoerner77 would you mind opening a Pull Request for this so we can test and (hopefully) merge it?

**Comment by mwoerner77** [comment]
https://github.com/LegoFigure11/RaidCrawler/pull/27

**Comment by mwoerner77** [comment]
I've been testing my build of it and it's worked for 2 shiny pokemon now (I'm selecting all new gen pokemon and running it). My only issue with what I have is the inability to search for a pokemon in the list with text.
