### ISSUE TITLE
Bug Report: Raidcrawler does not Go to Date and Time adjustment Menu

### ISSUE THREAD

**Issue by db2810** [LegoFigure11/RaidCrawler#25]
Raid crawler seems to miss the Date and Time Adjustment Menu with latest release. Adjusting "Open Date Change Delay" did not have intended effect as increasing or decreasing value from 200-5000ms always led to cursor stopping on "Time Zone" and changing time zone by 1 up press instead. 

I suspect a down press to Date and Time is missing and so it stops on time zone. Much appreciated!

For more context, routine was working fine on 1.0.4 release

**Comment by db2810** [comment]
Adjusting Open Sub Menu as well seems to have addressed the issue.

**Comment by db2810** [comment]
Adjusting open sub menu delay seems to have addressed the miss

**Comment by LegoFigure11** [comment]
I've increased the default submenu delay so that less people are affected by this
