### ISSUE TITLE
Game Version, Story Progress, and Event Progress can be accounted for automatically

### ISSUE THREAD

**Issue by Lincoln-LM** [LegoFigure11/RaidCrawler#28]
Accounting for this automatically would make the tool easier to use with the user not having to specify these.

Here are my impls for sv-live-map if it'll help get it set up here:

~~[Game Version](https://github.com/Lincoln-LM/sv-live-map/blob/85b075e8c2bd9af39be173dc48c5b1332a16e007/sv_live_map_core/raid_reader.py#L88)~~ Done in [e1976ac](https://github.com/LegoFigure11/RaidCrawler/commit/e1976acac56aa240b43ecfd95ce78b0bd0627167)

[Delivery Group Counts (this can also be included alongside the raid data that you have in the repo instead of read from memory)](https://github.com/Lincoln-LM/sv-live-map/blob/85b075e8c2bd9af39be173dc48c5b1332a16e007/sv_live_map_core/raid_reader.py#L36)

~~[Story Progress](https://github.com/Lincoln-LM/sv-live-map/blob/85b075e8c2bd9af39be173dc48c5b1332a16e007/sv_live_map_core/raid_reader.py#L58)~~ Done in [2d92907](https://github.com/LegoFigure11/RaidCrawler/commit/2d92907d8ff19c415630bf4d46501a1418ee2c7d)

**Comment by Lincoln-LM** [comment]
As an additional note, PKHex.Core could be leveraged to decrypt story progress instead of fully implementing that here

**Comment by LegoFigure11** [comment]
Game Version detection implemented in [e1976ac](https://github.com/LegoFigure11/RaidCrawler/commit/e1976acac56aa240b43ecfd95ce78b0bd0627167), I think we took a different approach to you but it achieves the same end result

**Comment by architdate** [comment]
@Lincoln-LM thanks for that! I see how you are figuring out story progress, but event progress is done from 0->3 (4 stages), We cannot correspond the story progress to event progress directly right? 

Do let me know if I am mistaken on that!

**Comment by Lincoln-LM** [comment]
@architdate I believe "stage" only determines which star raids from the event the game will allow, which is based on story progress. I am unsure as to why pkNX handles event stages in sets of 4 though.
https://github.com/kwsch/pkNX/blob/25bd24a0b8bad160a5031437dc90b1bc3cb9dd68/pkNX.WinForms/Dumping/TeraRaidRipper.cs#L110

**Comment by Lincoln-LM** [comment]
Taking another look, from a legality point of view it makes sense to combine 6/7 with the 5 star group as the requirement for 6 star is not based on story progress but instead how many dens completed.

**Comment by architdate** [comment]
I don't believe we actually even use delivery group counts since we just use the bcat data + raidblock to handle identifying raids, so that shouldn't be required i believe! (unless we want to eventually shift event raid detection to RAM as well). Closing for now!

Thanks for the help with GameVersion and Story Progress identification <3

**Comment by Lincoln-LM** [comment]
> I don't believe we actually even use delivery group counts since we just use the bcat data + raidblock to handle identifying raids, so that shouldn't be required i believe! (unless we want to eventually shift event raid detection to RAM as well). Closing for now!
> 
> Thanks for the help with GameVersion and Story Progress identification <3

i haven't looked into your implementation well, but i'm unsure how it could be future-proof if it doesn't use delivery groups at all? how would it handle an event with 2 different (non 7 star) encounter tables? what if charizard had an extra table on top of florges/mimikyu?
