### ISSUE TITLE
Advance Date Logic

### ISSUE THREAD

**Issue by SuperN0va** [LegoFigure11/RaidCrawler#29]
So me and my friends when hunting for 6star raid we found that in SV you dont have to really change the date when you try to advancing the date to get everything refresh, you just need to select everyting without change them from left to right one by one, and then click OK, home button back to game and everything will refresh. In this way raidcrawler can be a little bit faster and whats more the encounter date of pokemon will more likely to be the current time not a time from future(thats what my friend cares about lmao)

**Comment by LegoFigure11** [comment]
Wow this actually works, hilarious. I'm not sure if it's worth saving the extra 200ms/cycle for the number of people who will say "it's not changing the date, it's not working" so maybe I'll make it a setting? Nice find though, that's pretty funny.

**Comment by SuperN0va** [comment]
yep, become a setting will be good, thanku for your considering !
