### ISSUE TITLE
Ryujinx version ? 

### ISSUE THREAD

**Issue by Lukas-Craft** [LegoFigure11/RaidCrawler#30]
Hi, small question can we use this software on Ryujinx.  As the emulator is based on a CFW switch with an atmosphere folder. I thought it might work but I'm waiting for a confirmation. Thank you.

**Comment by LegoFigure11** [comment]
No, Ryujinx is not officially supported. You may potentially be able to get something working but I can’t imagine it’d be easy and I won’t be providing support. This program is designed to be used on official hardware using copies of the game that you actually own.
