### ISSUE TITLE
Incorrect Event Tera

### ISSUE THREAD

**Issue by TheLordLucyfer** [LegoFigure11/RaidCrawler#32]
**Describe the bug**
Incorrect Tera Listing in RaidCrawler

**To Reproduce**
Inject Seed on a Scarlet Save File and run RaidCrawler

**Expected behavior**
Expected a 5star 5IV 0 Speed Poison Tera Tyranitar, as per RaidCrawler's info, but in-game it is a Ghost Tera. IVs, nature, and Gender are all correct in-game when defeated.

**Raid Data**
01 00 00 00 07 00 00 00 01 00 00 00 09 00 00 00 68 57 CD 1F 00 00 00 00 02 00 00 00 00 00 00 00
Raid Block Absolute Address: 2D4478F040

**Screenshots**
![image](https://user-images.githubusercontent.com/83327543/206646782-045d4a02-6f99-46a0-97ec-c4de3fa724d6.png)

**Comment by architdate** [comment]
Hey, the latest commit "should" fix this. I'll close out this issue for now, if it persists for others, ill reopen this
