### ISSUE TITLE
Still getting Bad Read after removing all overlays

### ISSUE THREAD

**Issue by luigisp** [LegoFigure11/RaidCrawler#35]
**Describe the bug**
I am still getting the "bad read" error after having removed all overlays / other unnecessary homebrew apps from my emuMMC. Raid Crawler is able to connect to my Switch via Sys-bot (is able to execute "Advance Date") but is still unable to read raid dens.

**Additional context**
I am using a completed Scarlet save file which was "converted" into a Violet save file (so to clarify: I am playing Violet, but with a save file that was originally from Scarlet).

Dump:
08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 A0 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 70 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 01 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 A0 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 70 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 01 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 A0 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 70 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 01 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 A0 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 70 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 01 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 A0 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 70 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 01 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 A0 02 00 00 00 00 00 00 08 5B 62 58 11 00 00 00 08 5B 62 58 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by LegoFigure11** [comment]
What version of Scarlet/Violet are you on? Latest release will only work with v1.1.0 so please ensure it is fully updated.

**Comment by luigisp** [comment]
I'm on the latest version (v1.1.0).

Should I consider a fresh install of Atmosphere?

**Comment by LegoFigure11** [comment]
Yes, there must be something shifting your RAM still. A fresh install would be the next logical step.

**Comment by luigisp** [comment]
Ok I will do that and let you know if it fixes it - btw thank you so much for your time/effort and for making this tool :)

**Comment by viaa740315** [comment]
My game version is Violet(v1.10).
I also have the same problem.
I reinstalled the game and it doesn't fix it.

**Comment by LegoFigure11** [comment]
luigisp was able to resolve this issue by removing all atmosphere files from their SD card and doing a clean CFW install, my advice to you would be to try the same thing.
