### ISSUE TITLE
Speed up date skipping via touch screen

### ISSUE THREAD

**Issue by Lincoln-LM** [LegoFigure11/RaidCrawler#36]
Date skipping can be sped up by sending touch screen commands to navigate menus. Testing my implementation in sv-live-map vs the one here, the total time for a full cycle (including processing) is 22.82s vs 13.238s, 5 seconds of which in sv-live-map is just waiting for the game to process that the date skip happened (lol). Touch screen inputs work even if a switch is docked, and this speed increase definitely adds up over time (1000 date skips takes about 2.661666667 hours less).

https://github.com/Lincoln-LM/sv-live-map/blob/master/sv_live_map_core/automation_window.py#L249

**Comment by LegoFigure11** [comment]
Working on it as we speak ;)

**Comment by LegoFigure11** [comment]
No matter how hard I tried, I could not get this to be consistent https://github.com/Lincoln-LM/sv-live-map/blob/378d858e5543ae2f9402c7ff1fbbc1af87726bab/sv_live_map_core/automation_window.py#L288

So while mashing DDOWN is slightly slower than using the hold there, it results in considerably less missed cycles making it actually faster overall.

**Comment by Lincoln-LM** [comment]
that's odd, while I do get the occasionally dropped cycle, it's nowhere near enough to cause considerable delay. I'll do a comparison of mine vs mashing DDOWN to be sure I'm not missing something.

**Comment by Lincoln-LM** [comment]
within my framework (which admittedly may have some differences from how yours is handling it) mashing DDOWN gives an average of 16.2685737 seconds per date skip, and holding gives 13.2782966 seconds. Notably, holding DDOWN for only 0.05 seconds was not consistent for me, so these numbers are based on 0.1 per DDOWN. if it is to be assumed that I doubled the speed decrease by doing this, the mashing speed would instead be around 14.77343515. using the 14.77343515 number, in order for mashing to be faster overall, you would need to expect at least 1 failure via holding for every 8.881 successful skips. this is not at all the ratio that I'm seeing, so in my framework at least, holding should be faster. this does not even take into account the consistency increase USB connection would likely give, but RaidCrawler does not (yet?) support this anyway. if you really are seeing this much inconsistency when holding, it makes sense to mash instead, but I thought I might as well still post my numbers on it.

**Comment by Lincoln-LM** [comment]
> this is not at all the ratio that I'm seeing

for reference, I have just done 100 date skips without a single failure due to holding

**Comment by LegoFigure11** [comment]
Good to know, might just be a local thing to me. I'm dropping at least 50% of them
