### ISSUE TITLE
Raid Location Reported Incorrectly - South Province (Area 4) - Den 15 Reported at South Province (Area 5)

### ISSUE THREAD

**Issue by Abhiously** [LegoFigure11/RaidCrawler#4]
![image](https://user-images.githubusercontent.com/24847721/204105810-bd4054a5-7b38-47f7-a4c8-f1817f1f60a6.png)
 The location of this raid den on the map is within South Province Area 4.

![2023090205374400-B6CE40797459B0890BF7CEF68A4CE587](https://user-images.githubusercontent.com/24847721/204105903-9a9f41c9-6ec0-4680-9de1-83f0c4c48376.jpg)

This is location of the den on the map.

**Comment by architdate** [comment]
Can you show the whole window while reporting bugs? Was this the 6* raid? It should not be reporting locations incorrectly

**Comment by architdate** [comment]
Closing since there has been no response to the above. Please reopen if you can replicate properly.
