### ISSUE TITLE
Cetitan Raid not matching rewards

### ISSUE THREAD

**Issue by RebelEnforcer19** [LegoFigure11/RaidCrawler#41]
![Screenshot_20221213_091254](https://user-images.githubusercontent.com/120487817/207372182-0cd8c348-5c36-4624-9266-f3d6e12046a8.png)
![Screenshot_20221213_091328](https://user-images.githubusercontent.com/120487817/207372394-3837cebd-545e-4d9f-8988-e3446271d424.png)
This raid didn't have the right rewards as you see and matched everything like location and Pokémon was correct just the rewards did not match

**Comment by architdate** [comment]
(Last spicy herba would not be obtained) This should fix the issue you pointed out to me as well @LegoFigure11

**Comment by ReZeroEmiria** [comment]
I don't see this feature in the releases currently, would I need to compile this myself to see the rewards list?

If so is it as simple as putting it all in like Visual Studio and compiling/running?

**Comment by LegoFigure11** [comment]
@ReZeroEmiria clicking on the "build" shield in the readme will link you to a compiled version of the latest commit. It'll be added to a new release once we're sure it's ready.
