### ISSUE TITLE
in-game map does not match pop-out Raid Crawler Map

### ISSUE THREAD

**Issue by LightSanctity** [LegoFigure11/RaidCrawler#42]
I hope this is a bug/issue(?) but I figured I post if it was; apologies if it isn't. 

**Describe the bug**
Raid Crawler map pop-out does not correlate to the in-game map location. 
in-game map
![IMG_3196](https://user-images.githubusercontent.com/67592847/207670569-a787ebad-2ac4-40f7-a548-588e83d4ad65.jpg)

Raid Crawler
![Screenshot (11)](https://user-images.githubusercontent.com/67592847/207670278-7063c706-0d56-420d-a9d6-4e8d621aee09.png)

**Raid Data**
raid data was right, Ivs, items etc just not the location from the Raid Crawler Map. First one that ended up like this, but if I find another later; I will make note of it as well. 

So, I have not been able to replicate, so I will be closing. Apologies for posting/ wasting time. I am not sure what would cause it, but I am unable to get it again.

**Comment by LegoFigure11** [comment]
There are certain den ids that are mapped to multiple locations in-game, we're in the process of implementing this

**Comment by LightSanctity** [comment]
Cool! Sorry for prematurely closing. I thought it was just a me thing. Thanks for the work! :)
