### ISSUE TITLE
Can't move month time

### ISSUE THREAD

**Issue by aymlam** [LegoFigure11/RaidCrawler#44]
The "Advance date" funcion is nigh on worthless if it can't change the month too. Am I overseeing something?

**Comment by LegoFigure11** [comment]
It doesn't actually need to change the date as per #29, but if you want it to you can change "Number of days to skip" from 0 to 1 in the program settings

**Comment by LegoFigure11** [comment]
Also make sure that "synchronise clock with internet" is turned off in your switch settings

**Comment by aymlam** [comment]
Oh I see, thanks for the clarification.

**Comment by aymlam** [comment]
Awesome tool btw!
