### ISSUE TITLE
Help with delay timings

### ISSUE THREAD

**Issue by jawzoblivion** [LegoFigure11/RaidCrawler#45]
Can I get some help with the correct delay timings? I accidentally messed around with it a bit too much and now I can't get it to work.

**Comment by TheLordLucyfer** [comment]
This is what the defaults are from a fresh download of RaidCrawler if this helps you at all.
![image](https://user-images.githubusercontent.com/83327543/207995365-b378d0b1-f924-4df7-ac99-ff684c96b383.png)

**Comment by architdate** [comment]
Thanks @TheLordLucyfer for the help!
