### ISSUE TITLE
Shiny Locked Charizard False Positive

### ISSUE THREAD

**Issue by bbtheraidg** [LegoFigure11/RaidCrawler#47]
![2785359D-93EC-47BC-BC42-8EE06A4D74A4](https://user-images.githubusercontent.com/59871255/208056496-ef45e2b9-a825-4d76-baa7-130c8daf9539.jpeg)

I just wanted to let y’all know that I recently found a locked shiny char that was brute forced on game and could have been a bug that I need to pass on. Sadly the black charizard was not there lol 

I do hope that the seed info helps the team and I regret that I did not fully dump the raid for you.

**Comment by architdate** [comment]
Thanks for the report! The game anti shiny's the PID to make it not shiny for your specific TID, will handle this in the next release

**Comment by architdate** [comment]
Closed in https://github.com/LegoFigure11/RaidCrawler/commit/a9382dabf2e7c86e3a735ca02b416bb93c40b79a
