### ISSUE TITLE
Feature Request - Verbose IV Strings

### ISSUE THREAD

**Issue by LightSanctity** [LegoFigure11/RaidCrawler#49]
This is a minor request and I am unsure if it is possible or not but I suppose I will ask anyways if it is possible; what I wanted to know was would it be possible to denote what the IVs are and yes, I know I could look it up but seeing it on RaidCrawler would also be nice, too. i.e. HP 31 / Atk 31 and so on. Thanks!

**Comment by architdate** [comment]
Sorry, I don't understand what you mean exactly by this? Can you explain again?

**Comment by LightSanctity** [comment]
Yea, in Raid Crawler it has: 31/31/31/31/31/31 for example, could it do: HP 31/ Atk 31 / Def 31 ?

**Comment by ReZeroEmiria** [comment]
Could this be a toggle? I feel like it might overload the UI a bit, I personally prefer them without the explanation.
