### ISSUE TITLE
Incorrect Rewards on RaidCrawler's Newest Build

### ISSUE THREAD

**Issue by TheLordLucyfer** [LegoFigure11/RaidCrawler#50]
**Describe the bug**
The Rewards View is showing incorrect Raid Rewards for my current seed (can be supplied if needed to check) while the in-game reward is what is expected still. This only happens on the newest build, older builds showed the raid rewards correctly.

**To Reproduce**
Check raid data on current release vs the available build via the build button.

**Expected behavior**
In-game is still correct, but Crawler's reward viewer is inaccurate.

**Raid Data**
01 00 00 00 11 00 00 00 01 00 00 00 0B 00 00 00 19 17 BD 51 00 00 00 00 01 00 00 00 01 00 00 00

**Screenshots**
![image](https://user-images.githubusercontent.com/83327543/208218542-11f9d8ce-cfef-439c-82bc-24b01956581a.png)
![image](https://user-images.githubusercontent.com/83327543/208218585-57a5b67f-506b-44c3-b754-cb48983bdab3.png)
![image](https://user-images.githubusercontent.com/83327543/208218598-857975de-2770-4f6c-be68-a92554c8440f.png)
(And one Exp. Candy L extra)

**Additional context**
N/A

**Comment by BeginnerSlob** [comment]
I also encountered this bug.

**Comment by architdate** [comment]
Can you post the screenshot of the raidcrawler screen with seed unhidden?

**Comment by ReZeroEmiria** [comment]
How did you get a raid with 8 Herba Mystica? Do you need a sandwich for this or?
