### ISSUE TITLE
Issue with reading story progression 

### ISSUE THREAD

**Issue by shadowshadow725** [LegoFigure11/RaidCrawler#51]
I don't know whether it is an issue with the game's handling of gym badges or not but after completing the gym challenge without doing the badge for the 5th gym the program reads my progression state as 1 but my raids are actually from progression state 2.

**Comment by architdate** [comment]
I cannot replicate this issue unfortunately. Story progress code is taken from @Lincoln-LM 's sv-live-map repository and it seems to be working fine for most people!

**Comment by Lincoln-LM** [comment]
https://github.com/Lincoln-LM/sv-live-map/issues/42

This may be relevant

**Comment by Lincoln-LM** [comment]
> [Lincoln-LM/sv-live-map#42](https://github.com/Lincoln-LM/sv-live-map/issues/42)
> 
> This may be relevant

I have a definite case where the difficulty flag is not at the static offset raidcrawler uses. your impl may differ, but this is simply solved by searching nearby blocks for the correct key as the PR closing that issue does. @architdate

**Comment by architdate** [comment]
Hmm are we sure that the offset would be within +- 0x1000 range however? I wonder if a pointer can be found that always properly points to the block instead of checking the vicinity like this. Reopening for now

**Comment by Lincoln-LM** [comment]
> Hmm are we sure that the offset would be within +- 0x1000 range however? I wonder if a pointer can be found that always properly points to the block instead of checking the vicinity like this. Reopening for now

save blocks are sorted by key, in order to be outside of the 0x1000 range there would need to be 128+ save blocks between the default address and the actual address. the 0x1000 is only in place to prevent an infinite loop of reading. in reality, I would expect it to always be well within this 128 range. for difficulty specifically, the game actually searches through save blocks until it finds a matching key, so I wouldn't expect a pointer to exist that points to it directly.

**Comment by Lincoln-LM** [comment]
if consistency is the concern specifically, it probably wouldn't be hard to not use static offsets at all and search for blocks how PKHex does with normal saves. https://github.com/kwsch/PKHeX/blob/b8f6b5f434218bf291fbcef211008f50cd6eee25/PKHeX.Core/Saves/Access/SCBlockAccessor.cs#L112

**Comment by architdate** [comment]
PKHeX just runs a binary search over it, I think a linear search is fine since the space range to search in isn't large enough here anyway and it is something that only needs to be done once on boot

**Comment by Lincoln-LM** [comment]
I think searching based on the static offset with the assumption that it would be near it is good way to boost the efficiency of the search. PKHex's method was mentioned as searching over the entire space of the blocks would ensure this "consistency", though it would be a lot slower. Blocks being sorted in ascending order by key really lends itself well to the "work from assumed position" method of searching.
