### ISSUE TITLE
[QUESTION] It is possible to use the raids seeds instead of switch ip?

### ISSUE THREAD

**Issue by Phosky71** [LegoFigure11/RaidCrawler#53]
Hello, I am an emulator switch player, and I was searching about any app like raidcrawler for emulator but there isn´t any one. But i think that if we can use rng seed of daily raids and the seed of a especific raid we can use this on a switch emulator. 
![Captura de pantalla 2022-12-19 232149](https://user-images.githubusercontent.com/98740899/208538135-06f39e4f-0c70-4d5a-89e2-af091a1f2725.png).

Sorry for my english.

**Comment by Phosky71** [comment]
I think that if emulator player don´t use the auto mode, it is posible to use it with this metod

**Comment by architdate** [comment]
Unfortunately that is out of the scope of this project. Seed injection is equivalent to just genning the pokemon in :)
