### ISSUE TITLE
Banned switch

### ISSUE THREAD

**Issue by chapeyfor** [LegoFigure11/RaidCrawler#56]
Hi everyone, would like to be able to use the tool on a banned switch, is there a work around? Would appreciate some support.

**Comment by paulimp** [comment]
yes it is possible

**Comment by chapeyfor** [comment]
@paulimp can you explain how? i have tried while using specific DNS and IP address to ensure my switch is connected online, but still did not manage to connect the tool to my switch… 😭

**Comment by edwarbad23** [comment]
1) Download the software and open it
2) Install SysbotBase
3) In the switch active Wifi  and enter to the game (doesn't matter if you are banned)
4) copy the IP in your switch (don't use DNS or anything) and put on raidcrawler
5) Put connect and see the magic!! 

Remember you need to connect both joycons on the switch and don't use externals controllers (PRO, generic controller) and don't uses cheats or modded contents that change the RAM of the game

**Comment by chapeyfor** [comment]
Hi thanks for the step, that’s exactly what I am doing but connection keeps failing, see screenshot. Quick question, should the computer be on the same internet connection? Maybe that’s the issue there…
![Uploading 19CE3E7A-70D6-4EA6-9C8E-DAABC711BBA9.jpeg…]()

**Comment by chapeyfor** [comment]
![C0D4F37D-B00C-4DB7-84F5-59DD4D043745](https://user-images.githubusercontent.com/34949958/209720336-e806164d-ce3d-43e2-a6a7-48361f7a1691.jpeg)

**Comment by LegoFigure11** [comment]
Yes, that will be the problem

**Comment by chapeyfor** [comment]
Ahah well thanks, I need to connect my pc to the wifi then, not on ethernet 😅, I’ll try again tomorrow.

**Comment by chapeyfor** [comment]
Thanks a lot, connecting my computer to the same wifi as the switch made it work ^^. Amazing job with the tool guys, thanks

**Comment by lfmundim** [comment]
Just a PSA here, @chapeyfor 

I use my computer on ethernet and switch on wifi. The Crawler works fine. They are both off of the same router/modem, as in my eth cable comes off of the same router that is routing the wifi network for the switch. I don't know if thats what you tried previously

I have multiple routers at home and if I connect the switch to another one that is not the one providing eth to the pc, it doesn't work
