### ISSUE TITLE
Feature Request - Filter for pokemon with different forms

### ISSUE THREAD

**Issue by SnowyStarSky** [LegoFigure11/RaidCrawler#59]
Not sure if possible but would like to be able to include a form filter.

Eg. Maushold family of 3, & family of 4
Gastrodon east/west

Please close issue if not possible or has already been requested.

**Comment by architdate** [comment]
This should technically already be possible with batch filters. Just put `=Form=0` or `=Form=1` in the batch filter box and update your filter which would make it stop when that form is hit.

Note that batch filters are only available in the latest commit
