### ISSUE TITLE
UX Feature Request - Automatic Filtered View

### ISSUE THREAD

**Issue by jnovack** [LegoFigure11/RaidCrawler#61]
(This can be an option)

_Description_
When stop filters are enabled, show only the raids which match the filter.

_Expected Change_
I would like to see "<< 01 / 03 >>" rather than "<< 01 / 69 >>".

![image](https://user-images.githubusercontent.com/387006/210158308-2e38dc10-7370-413b-8f11-95b53a63050b.png)

_Benefit_
Currently, one must Shift-Click to get to the matches, which is not intuitive (a button having two different functions). Additionally, by including the current match over the total number of matches, you do not have to press `Shift->>` to check if there are more matches or forget to press it (when there could be more than one match) and potentially lose a match.

_Bonus Thoughts_
* Show the filter name which was matched under the "<< 01 / 03 >>".
* The "Enable Filters" button (suggested enhancement #62 ) , should swap between the Filtered (01 of 03) views or All (01 of 69) views.

**Comment by architdate** [comment]
I think a majority of the people would want to see all raids even when a filter does match. The proposed solution would make it unable to view other raids atall. 

On a side note It is also very unlikely that multiple raids matched filters (I had it happen only once myself) so most of the times you will only have 1 raid showing anyway.
