### ISSUE TITLE
UX Enhancement - "Disable?" should be reversed to "Enable"

### ISSUE THREAD

**Issue by jnovack** [LegoFigure11/RaidCrawler#62]
Reverse the "Disable?" checkbox to be an "Enable Filters" checkbox.

It is somewhat counter-intuitive to enable a checkbox to disable something.

**Comment by LegoFigure11** [comment]
Should the individual raid filters also be updated accordingly?
![image](https://user-images.githubusercontent.com/24732684/211196594-7a13ac40-42de-48ed-9824-7b579803590d.png)

**Comment by jnovack** [comment]
Yes, good eye.   I'll make a new issue someone can grab at their leisure.
