### ISSUE TITLE
UX Bug - Inconsistency in Data Presentation during Searching

### ISSUE THREAD

**Issue by jnovack** [LegoFigure11/RaidCrawler#64]
**Describe the bug**
While running "Advance Date" searching with filters, not all the data is removed and shown.  Either all data should be shown, or all data should be removed.

**To Reproduce**
If applicable, please list the steps to reproduce the behavior:
1. Advance the Date without Stop Filters (to set data initially)
2. Advance the Date with Stop Filters enabled.
3. Tera Icon, Pokemon Icon, Seed, Tera Type, Encryption Constant, PID, Area, and Difficulty are populated and change during each date change.

**Expected behavior**
Either all data should be shown, or all data should be removed.  Since the data is refreshed, permitting the user to browse, all data should be shown.

**Screenshots**
<img width="309" alt="image" src="https://user-images.githubusercontent.com/387006/210162341-8d4ddf34-9816-4a89-a7b3-a3e34ea6b20b.png">

**Comment by jnovack** [comment]
This only occurred during the event.  Now that the event is over, this bug is no longer reproducible but may still exist during events.

**Comment by architdate** [comment]
It should be showing all data. I assume perhaps the story progression/event progression is set incorrectly which caused a data mismatch somehow. I will keep this open however to test during the next cinderace event

**Comment by jnovack** [comment]
I was using the latest (downloaded said v1.0.9, but it doesn't look like the version in the application settings was changed, still showed v1.0.8).  And Cinderace wasn't showing, all the Cinderaces/Gyarados/Gengars (the first 5, marked as "event") were showing as Delibirds.

**Comment by architdate** [comment]
Ah I see, I suggest you use the latest commit that you can download through GitHub actions or by clicking on the build badge in the readme. This issue should be fixed as of the latest commit already
