### ISSUE TITLE
Proposed Webhook Default Content

### ISSUE THREAD

**Issue by jnovack** [LegoFigure11/RaidCrawler#66]
Shiny:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/387006/210193192-5513ccab-a764-4b81-bbce-9a4eaea1e264.png">

Non-Shiny:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/387006/210193008-017acdeb-fc8d-43d0-9b4d-c8d9ee57d440.png">

```json
{
  "content": null,
  "embeds": [
    {
      "title": "Miriadon (Ice)",
      "color": 16763904,
      "fields": [
        {
          "name": "Difficulty",
          "value": "⭐⭐⭐⭐⚝⚝⚝"
        },
        {
          "name": "Ability:heavy_minus_sign::heavy_minus_sign::heavy_minus_sign:",
          "value": "Something",
          "inline": true
        },
        {
          "name": "Nature:heavy_minus_sign::heavy_minus_sign:",
          "value": "Rash",
          "inline": true
        },
        {
          "name": "Gender:heavy_minus_sign::heavy_minus_sign:",
          "value": "Genderless",
          "inline": true
        },
        {
          "name": "Moveset",
          "value": "Tackle\nSplash\nFlail\nHyper Beam",
          "inline": true
        },
        {
          "name": "|",
          "value": ".",
          "inline": true
        },
        {
          "name": "Extra Moves",
          "value": "Light Screen\nReflect",
          "inline": true
        },
        {
          "name": "HP",
          "value": ":white_check_mark:",
          "inline": true
        },
        {
          "name": "Atk",
          "value": ":white_check_mark:",
          "inline": true
        },
        {
          "name": "Def",
          "value": "`23`",
          "inline": true
        },
        {
          "name": "Speed",
          "value": ":zero:",
          "inline": true
        },
        {
          "name": "SpA",
          "value": ":white_check_mark:",
          "inline": true
        },
        {
          "name": "SpD",
          "value": "`28`",
          "inline": true
        }
      ],
      "author": {
        "name": "✨ Shiny ✨"
      },
      "footer": {
        "text": "1x Salty Herba Mystica\n2x Bitter Herba Mystica\n1x Bottle Cap"
      },
      "thumbnail": {
        "url": "https://img.pokemondb.net/sprites/scarlet-violet/normal/miraidon.png"
      }
    }
  ],
  "username": "Custom Username",
  "avatar_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Pok%C3%A9mon_Ice_Type_Icon.svg/2048px-Pok%C3%A9mon_Ice_Type_Icon.svg.png",
  "attachments": []
}
```

Notes:
* The `:heavy_minus_sign:` are necessary to format the columns correctly.
* The `:green_check_mark:` is to visually distinguish perfect IVs at-a-glance.
* The `:zero:` is to visually distinguish a `No Good` IV at-a-glance.
* Tera Type Icon in the `avatar_url` from Wikimedia commons, would just need an array to hold them.
* `username` should be customizable in options
* `author` should ONLY exist (with the emojis) IF Shiny
* The embed `color` was chosen specifically when Shiny.
* Default embed `color` is `5814783`

----

I'm not sure where to put the filter it matched.  Maybe in the `content` field?
<img width="531" alt="image" src="https://user-images.githubusercontent.com/387006/210193703-e926f3f3-f6c1-41dc-8ec0-6fc5bff13722.png">

**Comment by architdate** [comment]
Some notes for this: the pokemondb image can't be used realistically, it needs to be from pkhex.drawing.dll

The IVs I prefer to be the way I already have it (in 1 field instead of 6 separated fields just for compactness)

The current embed color mimics the teratype. I feel your shiny notation above is enough to convey that a pokemon is shiny however (as part of author name) I don't want people to confuse a shiny Pokemon as an electric teratype by changing the embed color

I do like rewards in footer though! I'll implement this eventually

**Comment by jnovack** [comment]
> it needs to be from pkhex.drawing.dll

Can you elaborate on the reasoning for this?  I find the sprites really displeasing to the eye.

> The IVs I prefer to be the way I already have it 

I'm torn between compactness and quickness.  The green_check_mark option registers instantly (without reading) whether something is a Perfect IV or not, and you can glance at the picture for milliseconds and understand if (example) Special Attack is perfect or not.  However, it takes up a lot of space. The compact method requires more thought computation and deciphering, but it is compact.  I shall compromise.  Can I interest you in a hybrid that's a little easier to read?

`31 • 31 • 03 • 12 • 00 • 15`

`✅ • ✅ • 03 • 12 • 00 • 15`

My goal here is to limit the amount of time someone needs to look at the notification.  It's only meant to be a "poke", it is not meant to be an entire encyclopedia article, where you sit down to read it with your coffee like a morning newspaper.

Which brings me to my next point.  The more time we spend on this, the more time I realize that we don't need moveset.  From a notification point of view, who cares?  Are you going to do anything different if the moveset is there or not?  No, you are still going to back to the application (you have to disconnect the controllers!) and you can read the details there.

The notification drives you back to the application.   Email notifications don't have the entire body in the notification.  Tinder notifications don't have the entire profile in the notification.  Short, and sweet.  Unlike my rambling in this post. :/

> The current embed icon color mimics the teratype. 

I have the icon as the tera type.  Again, my whole goal is to not want to distract from the eye.  The tera type is definitely not more important than a shiny indicator.  Additionally, when looking at the list of multiple notifications, you get a rainbow of colors.  In this manner, a set of two colors (shiny, not-shiny) distract less.  

Remembering that you still have to go back to the application to disconnect the controllers, do you want "tera type" to be more prominent or "shiny" to be more prominent.  Has there ever been one person who said "YES! A FIRE TYPE WOOPER!!"?

--

For continued discussion, I present version 2.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/387006/211328181-078b79fb-8e89-4575-8fac-c886d317d875.png">

```json
{
  "content": null,
  "embeds": [
    {
      "title": "Miriadon",
      "color": 16763904,
      "fields": [
        {
          "name": "Difficulty",
          "value": "⭐⭐⭐⭐⚝⚝⚝"
        },
        {
          "name": "Ability:heavy_minus_sign::heavy_minus_sign::heavy_minus_sign:",
          "value": "Something",
          "inline": true
        },
        {
          "name": "Nature:heavy_minus_sign::heavy_minus_sign:",
          "value": "Rash",
          "inline": true
        },
        {
          "name": "Gender:heavy_minus_sign::heavy_minus_sign:",
          "value": "Genderless",
          "inline": true
        },
        {
          "name": "TeraType",
          "value": "Psychic",
          "inline": true
        },
        {
          "name": "IVs",
          "value": "✅ · ✅ · 03 · 12 · 00 · 15",
          "inline": true
        }
      ],
      "author": {
        "name": "✨ Shiny ✨"
      },
      "footer": {
        "text": "1x Salty Herba Mystica\n2x Bitter Herba Mystica\n1x Bottle Cap"
      },
      "thumbnail": {
        "url": "https://img.pokemondb.net/sprites/scarlet-violet/normal/miraidon.png"
      }
    }
  ],
  "username": "Custom Username",
  "avatar_url": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfigqvg-3ffa9208-8e56-4118-ab9c-837758d8b250.png/v1/fill/w_1280,h_1280,strp/tera_type_psychic_symbol_by_jormxdos_dfigqvg-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTI4MCIsInBhdGgiOiJcL2ZcL2U4ZGRjNGRhLTIzZGQtNDUwMi1iNjViLTM3OGM5Y2ZlNWVmYVwvZGZpZ3F2Zy0zZmZhOTIwOC04ZTU2LTQxMTgtYWI5Yy04Mzc3NThkOGIyNTAucG5nIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.PbaKMCJpuFwE3vfWVyUZ2-WPzKRNhRuG7sNKW2XJGp0",
  "attachments": []
}
```

**Comment by LegoFigure11** [comment]
>I'm torn between compactness and quickness. The green_check_mark option registers instantly (without reading) whether something is a Perfect IV or not, and you can glance at the picture for milliseconds and understand if (example) Special Attack is perfect or not. However, it takes up a lot of space. The compact method requires more thought computation and deciphering, but it is compact. I shall compromise. Can I interest you in a hybrid that's a little easier to read?
>31 • 31 • 03 • 12 • 00 • 15
>✅ • ✅ • 03 • 12 • 00 • 15
>My goal here is to limit the amount of time someone needs to look at the notification. It's only meant to be a "poke", it is not meant to be an entire encyclopedia article, where you sit down to read it with your coffee like a morning newspaper.

I've always been more of a fan of 31 - call me old fashioned but I think most of us Pokemon fans are hardcoded to look for the number 31 at this point and I personally find ✅ _slower_ to mentally parse. It also makes my mind jump to "Hyper Trained", so I would prefer we just stick to numerals. I would be willing to poll a group of end users as to which they find better though, or make it configurable so users can choose for themselves.

>Which brings me to my next point. The more time we spend on this, the more time I realize that we don't need moveset. From a notification point of view, who cares? Are you going to do anything different if the moveset is there or not? No, you are still going to back to the application (you have to disconnect the controllers!) and you can read the details there.
>The notification drives you back to the application. Email notifications don't have the entire body in the notification. Tinder notifications don't have the entire profile in the notification. Short, and sweet. Unlike my rambling in this post. :/

A usecase I have seen for these notifications is having the webhook post to a channel shared with everyone who will be taking part in the raid. I play in handheld 99% of the time, so I rarely if ever need to go back to the program and disconnect the controllers. Having the moves included in the notification means I don't have to do anything other than click the screenshot button and I have a lobby full of participants armed with knowledge of the moveset, which can go a long way towards beating some of the harder bosses. Sure, I could send a screenshot of the main window as well but that's just creating extra clicks for no reason. My point is, these notifications are serving as _more_ than just a poke to the host.

>I have the icon as the tera type. Again, my whole goal is to not want to distract from the eye. The tera type is definitely not more important than a shiny indicator. Additionally, when looking at the list of multiple notifications, you get a rainbow of colors. In this manner, a set of two colors (shiny, not-shiny) distract less.
>Remembering that you still have to go back to the application to disconnect the controllers, do you want "tera type" to be more prominent or "shiny" to be more prominent. Has there ever been one person who said "YES! A FIRE TYPE WOOPER!!"?

I'm with archit on this one and would rather stick with what we have -- I think a consistent icon is less distracting, and the embed color representing the type is faster to visually parse, especially as it's what people are already used to. I also feel that the shiny text in the header is sufficient (or <MonName ⭐> (open to using ✨ instead) like it is currently) and don't want people to mistake the yellow for an Electric-type raid.

---

Some other comments:
* I really like having the name of the filter that got hit included in the embed (or at the very least in the message). It's useful to know exactly what I'm getting at a glance, and is early enough in the embed that it shows up in the notification preview on my phone, so I don't even have to open discord to know what I've found, so I think that should be added back in.
* Using ➖ as a separator is not aesthetically pleasing on light mode (especially on mobile)
  * Desktop:
![image](https://user-images.githubusercontent.com/24732684/211792927-590dd634-f1bc-4684-828b-c44e3899c498.png)
  * Mobile:
![image](https://user-images.githubusercontent.com/24732684/211793132-528f5b1f-7283-42ec-9108-bf3c6af0d023.png)
* I also feel that the ⭐⭐⭐⭐⚝⚝⚝ notation for difficulty is confusing, would rather we just stick to ⭐ and don't bother with `⚝`.  The `⚝` is just visual clutter and the inconsistent line height with the emoji is distracting.
* I do really like having the rare drops in the footer, that's an excellent addition.

**Comment by jnovack** [comment]
>  31 vs ✅  - make it configurable so users can choose for themselves.

Deal!  Although, we're going to need a new options window at some point.  It's becoming quite unwieldy :)

> ...click the screenshot button...

I did not realize that it sent to the webhook.  I just assumed it saved locally.  That does make more sense.  Again, how about an option for which sections to include in the webhook?

> ...embed color...

Well, since we're doing options...

> I really like having the name of the filter that got hit included in the embed..

I did too, I like it where it is currently.  I overlooked putting it in the proposal.  The filter is great!

>  ...light mode ...

And you call yourself a programmer...

>  stick to ⭐ and don't bother with ⚝.

I was hating that yesterday too.  I agree.

> rare drops in the footer

Going to take extra coding to compound (2x Bitter) but I don't think that'll be a problem.

-----

The big question now is, how can we make the options screen better?  It's getting large.  Shall I make it a little larger and use Tabs for sections?

**Comment by architdate** [comment]
> Can you elaborate on the reasoning for this? I find the sprites really displeasing to the eye.

So the reason for this is all of our species data is based on internal game numbering which pkhex uses which may or may not align with species numbering/naming used by other sites (For example gholdengo is widely regarded as a pokemon whose national dex number is 1000, but that is not the case internally based on species IDs) I don't mind using external assets as long as a proper mapping can be made from all pkhex speciesIDs to sprite urls externally

**Comment by architdate** [comment]
Also since we merged the settings tab options, you can now expand upon webhook configurations in one of the tabs and call it notification settings perhaps

**Comment by jnovack** [comment]
Yeah, I did notice that the raid number for the pokemon did not match up with the dex number. I assume there was a reason for that at PokéHQ.

I was thinking of just making a `NationalDex.cs` structure and doing the reverse mapping (name to id), so we can perhaps image link to serebii since they have shinies or upload them into github as a repo.

> ...embed color...

The more I look at it, the more I like the teratype as the embed color.  Good call.  I'll still make it an option though.

**Comment by ViolentSpatula** [comment]
![image](https://user-images.githubusercontent.com/1721069/212322428-0c910536-88f6-48bd-8a65-9ebdd6376038.png)
![image](https://user-images.githubusercontent.com/1721069/212322635-134685c0-1e3e-4104-9dd4-d20de05e54a4.png)
![image](https://user-images.githubusercontent.com/1721069/212328025-b6a40bdc-37f7-47b1-8589-4aad8821f46b.png)
![image](https://user-images.githubusercontent.com/1721069/212330779-4f82f45a-d142-4858-8004-986d8973e6fa.png)
![image](https://user-images.githubusercontent.com/1721069/212330844-79fb192c-8ba3-4063-846d-0ae6db631bc9.png)


I'm working on a rework of the webhook to make it as informationally dense as possible, when it's complete it will include:
-Toggles for displaying IVs as only numbers
-Settings to select default emoji/Unicode characters
-Toggles for information

This way you can make the webhook look the way you want it to

**Comment by architdate** [comment]
This looks quite good too.

I am not sure what the search time here is though! Seems solid regardless, I see you have condensed down the gender, teratype and shininess all to the webhook title which is smart.

**Comment by ViolentSpatula** [comment]
I added search time a couple weeks back and I've been too timid to share lol
We got tired of wondering how long we had searched so I added it to the webhook and then added a ticker to the main window

**Comment by jnovack** [comment]
That looks much better than my garbage suggestion.

**Comment by ViolentSpatula** [comment]
![image](https://user-images.githubusercontent.com/1721069/212441455-43aca6b9-826c-4f18-86cc-bddf5b8d9e93.png)
![image](https://user-images.githubusercontent.com/1721069/212441467-5fb80d28-b469-4a4f-9ef0-cee52aad8219.png)
![image](https://user-images.githubusercontent.com/1721069/212441480-c03a0ff7-e8bc-4c3d-8d70-0653ae370803.png)
IV style setting is in
