### ISSUE TITLE
Error on latest nightly: Decoded uoffset_ had value less than 4.

### ISSUE THREAD

**Issue by pla-sma** [LegoFigure11/RaidCrawler#69]
encountering an error using latest nightly (04/01/23), if I use an older version, it works fine. Seems it crashes on the event raid part when reading raids.

![image-2](https://user-images.githubusercontent.com/56777153/210676313-23753547-4849-4d3d-a99a-834b78d3c891.png)

**Comment by jnovack** [comment]
Can you post the details please?

Please use code brackets to format properly.

**Comment by pla-sma** [comment]
thought this would be easier.
![image-3](https://user-images.githubusercontent.com/56777153/210679283-8b659188-4e55-4cba-b6b2-356d9c49f2af.png)

**Comment by architdate** [comment]
I cannot replicate this sadly, but i will add handling in case the flatbuffer for raid delivery doesn't parse

**Comment by architdate** [comment]
should be closed in the latest commit hopefully, let me know if it still persists
