### ISSUE TITLE
Advance date bot doesn't work properly

### ISSUE THREAD

**Issue by REIM729** [LegoFigure11/RaidCrawler#7]
Here's a record.
By the way I'm using a switch lite.

https://user-images.githubusercontent.com/116887562/204112334-e9ff3265-55cf-4a99-99a5-59101e9356e7.mp4

**Comment by architdate** [comment]
The program does not support switch lite yet since hacking switch lite without a modchip is not possible as of now. Will see what changes can be made to support switch lite

**Comment by REIM729** [comment]
My switch lite is already hacked with a modchip, and other things like Sysbot and LiveHex can work properly.

**Comment by architdate** [comment]
Right, what I am saying is that key delays are based on the normal switch and not switch lite. Needs additional research for setting navigation delays on switch lite to handle this case.

**Comment by LegoFigure11** [comment]
It seems that Switch Lites lack the "Update Dock" setting that the other consoles have, hence why it is scrolling too far. I'll try to find a button combo that works for both regular and lite, but testing will be difficult as I do not own a switch lite.

**Comment by LegoFigure11** [comment]
Fixed in the next release. "Open Settings" -> "DDOWN inputs to navigate settings" and then lower the value until it works for you.
