### ISSUE TITLE
Change the "Disable Filter?" checkbox to be consistent and intuitive

### ISSUE THREAD

**Issue by jnovack** [LegoFigure11/RaidCrawler#74]
Per #68 and #62 

Change the "Disable Filter?" checkbox to be consistent and intuitive.  

- Rename checkbox to "Active" (or "Enabled?")
- Reverse any logic, as necessary

![image](https://user-images.githubusercontent.com/387006/211372548-73d5afd7-13a7-4cf8-afc2-67a42a3cab2f.png)

I see you are still looking for a 0a0s Ditto, also. :)

**Comment by architdate** [comment]
For this i was wondering maybe if we change listbox to a checked listbox instead and just get rid of that checkbox
