### ISSUE TITLE
White Screen on Launch

### ISSUE THREAD

**Issue by janclem** [LegoFigure11/RaidCrawler#75]
**Describe the bug**
After update to reelease 1.0.9 when I launch RaidCrawler it shows up in my task bar but doesn't open up on desktop and when hovering over the icon it just shows a white window for the RaidCrawler window.

**To Reproduce**
If applicable, please list the steps to reproduce the behavior:
1. Download the latest release
2. Launch RaidCrawler via .exe

**Expected behavior**
GUI launches 

**Screenshots**
[Pic](https://gyazo.com/d3e0febdef5d3d422d5d50ad543ba271)

**Comment by jnovack** [comment]
In the main README file, click "build passing" image to get the nightly build.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/387006/211678116-cd0e42fc-b990-4f55-87b0-24a01589062f.png">

**Comment by pifopi** [comment]
You can also try to delete your settings in C:\Users\XXXX\AppData\Local\RaidCrawler
That did the trick for me :)

**Comment by janclem** [comment]
> In the main README file, click "build passing" image to get the nightly build. Does it happen there?
> 
> <img alt="image" width="403" src="https://user-images.githubusercontent.com/387006/211678116-cd0e42fc-b990-4f55-87b0-24a01589062f.png">

nightly link does not work for me

**Comment by LegoFigure11** [comment]
@janclem try this ink instead: https://github.com/LegoFigure11/RaidCrawler/suites/10272710948/artifacts/504382354

**Comment by janclem** [comment]
That link works, thanks Lego

**Comment by janclem** [comment]
Latest nightly launches without white screen issue

**Comment by DebeshMishra** [comment]
I am facing the same problem with the latest commit I tried today. But the funny thing is this only happens when I was replacing old raidcrawler with newer version. Installing in fresh directory works fine.

This is the image link:
https://media.discordapp.net/attachments/1003467011726258196/1063706401135919204/image.png?width=1191&height=670

**Comment by jnovack** [comment]
known issue. should be fixed shortly.
try this ink instead: https://github.com/LegoFigure11/RaidCrawler/suites/10272710948/artifacts/504382354

@architdate Can you tag any working main commit as v1.0.10 so we aren't running into this issue?

**Comment by architdate** [comment]
@jnovack his issue is on the latest commit he tried today though. That should not have happened with the latest commit

**Comment by pifopi** [comment]
I had the same and wiping my settings fixed it. Could it be it fails to loads some settings?
