### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by LsPartida** [LegoFigure11/RaidCrawler#76]
**Describe the bug**
When open the app, just show the icon on the windows app bar, but wont show nothing, and when doing alt + tab just show the aplication without controls (inputs, checkboxes, buttons) and won't put it on front of desktop.

**To Reproduce**
Don't know how to reproduce and there's no logs, Microsoft Windows Versión 10.0.22000.1455

**Expected behavior**
To open the application

**Raid Data**
N/A
**Screenshots**
![image](https://user-images.githubusercontent.com/47125505/212167721-e3bdf69e-27a7-4111-9818-962916d03156.png)
![image](https://user-images.githubusercontent.com/47125505/212167742-ab54e858-4fcc-4c7d-8759-39b36e325739.png)
![image](https://user-images.githubusercontent.com/47125505/212167770-94b3b327-8dc7-462a-8e9f-d73bd1c83cb5.png)

**Additional context**
It worked propertly before and there's no windows update or something new on the system

**Comment by jnovack** [comment]
known issue.  should be fixed shortly.
try this ink instead: https://github.com/LegoFigure11/RaidCrawler/suites/10272710948/artifacts/504382354
