### ISSUE TITLE
Time to Display Form

### ISSUE THREAD

**Issue by jnovack** [LegoFigure11/RaidCrawler#83]
What's happening after the "double-click to Open" and the display of the form?

On my machine (Surface from at least 6 years ago), it takes at least 15 seconds from "double-click" to showing the first form, are other people experiencing this?  Should we show a (*shudder*) splash.. page?

**Comment by architdate** [comment]
Sorry I don't exactly understand the issue here? Like you are saying it takes a while for the form to show up?

**Comment by jnovack** [comment]
Yes.  Double-click the EXE.  How long does it take before the form shows up?

**Comment by pifopi** [comment]
Yes, it is also long for me. I guessed it was linked to all the files the app was loading ? Not sure how to profile things in C# though

**Comment by pifopi** [comment]
It takes about 5s on my main machine, 15s on my "server" machine where the CPU isn't as good

**Comment by architdate** [comment]
So on boot we are decrypting and reading into memory the game flatbuffers as well as raid locations, so this startup time may be unavoidable. I am not really too fond of a splash screen idea however. Open to suggestions though! (Startup code would be the MainWindow() code prior to initialize component: https://github.com/LegoFigure11/RaidCrawler/blob/main/MainWindow.cs#L51-L83

**Comment by jnovack** [comment]
Yeah, I'm not fan of a splash screen either, but leaving everything invisible until wake up is confusing to the user.  Prior to understanding the delay, I was opening multiple copies.

**Comment by architdate** [comment]
Maybe something like what PKHeX displays then on startup. I'll look into this then.

**Comment by jnovack** [comment]
The program doesn't auto-connect, so there is always a delay between program instantiation and pressing the "connect" button.  Can we utilize that time more effectively?

Instantiate the window immediately, then enable the "Connect" button after everything is loaded?  Maybe even a "Loading assets 2/5" in the status line?

**Comment by kwsch** [comment]
Shouldn't need to splash screen. Without profiling the code, I can only assume that a major hang-up is the FlatSharp reflection generating the de-serialization code for reading the gamedata.

FlatSharp's latest 7.0.0 release supports compile-time code generation. Since there are only a few FlatBuffer formats needing to be read, shouldn't be too much effort needed to convert pkNX's definitions back to `fbs` to let the FlatSharp compiler rebuild them.

**Comment by kwsch** [comment]
Running a profiler myself, I can confirm that the majority of startup cost is from FlatSharp as described.
![image](https://user-images.githubusercontent.com/6393368/213955635-c3d10e0b-a7d7-449b-8f2b-5ddcb86f3888.png)

If the repo changes to instead generate classes at compile time, then the program will start up within a second.

Can also improve further if you replace the Netwonsoft.Json with the [System.Text.Json implementation](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/), which also has code-generation capability > reflection.

**Comment by Koi-3088** [comment]
Is this still an issue after the recent commits? FlatSharp was updated and somewhat optimized, `Newtonsoft.Json` was replaced with `System.Text.Json`.
