### ISSUE TITLE
East Province (Area 1) - Den 2 has bad location markers

### ISSUE THREAD

**Issue by jnovack** [LegoFigure11/RaidCrawler#92]
**Describe the bug**
East Province (Area 1) - Den 2 is listed on both the east and west of the map.  The left-most icon is definitely wrong, and the right-most icon is in the wrong province (it is in Area 2).

**To Reproduce**
If applicable, please list the steps to reproduce the behavior:
1. Get a match for 'East Province (Area 1) - Den 2
2. Open Map

**Screenshots**
![image](https://user-images.githubusercontent.com/387006/212544827-5f4a402a-0d41-45ae-be51-0cb4b4c1395e.png)
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/387006/212544977-24240036-1fc9-4c43-b51c-939561313a99.png">

The correct location is the Rock den under my player icon.

**Additional context**
if you help me out with how these coordinate systems work, I could fix.

**Comment by architdate** [comment]
So coordinate systems are based on data dumped from the game. The original file is taken from here: https://github.com/Lincoln-LM/sv-live-map/blob/master/resources/den_locations.json

The map locations are then deduced from that using the logic here: https://github.com/LegoFigure11/RaidCrawler/blob/main/MainWindow.cs#L673-L697

**Comment by jnovack** [comment]
It's not an issue with us, unless we don't have the newest coords list.

https://github.com/Lincoln-LM/sv-live-map/issues/63

**Comment by Koi-3088** [comment]
Closing as "close enough" (icons not perfectly positioned, but within margin of error, and dupes have been eliminated) unless some major discrepancies are reported.
