### ISSUE TITLE
Fatal error in dev builds

### ISSUE THREAD

**Issue by tombomb** [LegoFigure11/RaidCrawler#97]
(I know Dev builds are not supported but figured I would post the crash dump encase y'all want it)

**Describe the bug**

**To Reproduce**
If applicable, please list the steps to reproduce the behavior:
1. Get the latest dev builds from the action's
2. Download the latest artifact
3. Have the bot find something with a filter
4. Do the raid
5. Click Read Raids or Advance Date

**Expected behavior**
No error

**Raid Data**
01 00 00 00 07 00 00 00 01 00 00 00 04 00 00 00 7A 16 76 BD 00 00 00 00 00 00 00 00 00 00 00 00

**Screenshots**
![image](https://user-images.githubusercontent.com/544509/212565970-df4a08e6-b8ce-42a4-9083-078edf3ca55c.png)
![image](https://user-images.githubusercontent.com/544509/212566034-fa0dff86-297f-45c9-9461-92f14a412d64.png)
![image](https://user-images.githubusercontent.com/544509/212566144-5c04f134-15e4-4353-9374-ad43d384af9f.png)

**Additional context**
https://gist.github.com/tombomb/0e13de5c6e3e7b50407ff088ae742148

**Comment by jnovack** [comment]
> Get the latest dev builds from the action's

Can you give a link or at least a commit hash?

**Comment by LegoFigure11** [comment]
>An existing connection was forcibly closed by the remote host.

This usually happens when the program has disconnected from your switch without using the Disconnect button. Had the switch entered sleep mode or anything else that may have caused it to disconnect?

**Comment by tombomb** [comment]
only thing that changed was undocking to do the raid, it dident sleep

**Comment by tombomb** [comment]
> > Get the latest dev builds from the action's
> 
> Can you give a link or at least a commit hash?

https://github.com/LegoFigure11/RaidCrawler/actions/runs/3923936220

I also have the webhooks on, have not tested it with them off

**Comment by LegoFigure11** [comment]
I'm unable to repro but I'll leave this open for now in case someone else can

**Comment by architdate** [comment]
I am also unable to replicate this as of now. Unsure how to exactly get this issue

**Comment by architdate** [comment]
Does not seem like it can be replicated, so closing for now
